### ISSUE TITLE
Another NumberFormatException on LolChampionsCollectionsChampionMinimal

### ISSUE THREAD

**Issue by obed-vazquez** [stirante/lol-client-java-api#36]
It seems to be the same pattern that #34 

### Steps to reproduce
- Obtain the available champions for the summoner in the client.
- Call endpoint (without body payload):
`GET` `/lol-champions/v1/owned-champions-minimal`
- Returns a `GetLolChampionsV1OwnedChampionsMinimal` 
mapped to `lol-client-java-api`'s [`LolChampionsCollectionsChampionMinimal`](https://github.com/stirante/lol-client-java-api/blob/master/src/main/java/generated/LolChampionsCollectionsChampionMinimal.java)

Exception Trace:
``` 
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected a long but was 18446744073709550616 at line 1 column 19648 path $[23].purchased
        at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:321) ~[white-lolpicker-client.jar:na]
        at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:311) ~[white-lolpicker-client.jar:na]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:161) ~[white-lolpicker-client.jar:na]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:266) ~[white-lolpicker-client.jar:na]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[white-lolpicker-client.jar:na]
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[white-lolpicker-client.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:1058) ~[white-lolpicker-client.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:1016) ~[white-lolpicker-client.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:959) ~[white-lolpicker-client.jar:na]
        at com.google.gson.Gson.fromJson(Gson.java:927) ~[white-lolpicker-client.jar:na]
        at com.stirante.lolclient.ClientApi.getResponse(ClientApi.java:545) ~[white-lolpicker-client.jar:na]
        at com.stirante.lolclient.ClientApi.executeGet(ClientApi.java:453) ~[white-lolpicker-client.jar:na]
        at org.white_sdev.white_gaming.white_lolpicker_beans.model.bean.persistence.player.Player.getApiAvailableChampions(Player.java:123) ~[white-lolpicker-client.jar:na]
        at org.white_sdev.white_gaming.white_lolpicker_beans.model.bean.persistence.player.Player.getClientAvailableChampions(Player.java:119) ~[white-lolpicker-client.jar:na]
        at org.white_sdev.white_gaming.white_lolpicker_client.view.WhiteLoLPickerClientFrame$1.onClientConnected(WhiteLoLPickerClientFrame.java:51) ~[white-lolpicker-client.jar:na]
        at com.stirante.lolclient.ClientApi.setupApiWithLockfile(ClientApi.java:230) ~[white-lolpicker-client.jar:na]
        at com.stirante.lolclient.ClientApi.checkClientProcess(ClientApi.java:271) ~[white-lolpicker-client.jar:na]
        at com.stirante.lolclient.ClientApi.lambda$startProcessWatcher$0(ClientApi.java:295) ~[white-lolpicker-client.jar:na]
        at java.base/java.lang.Thread.run(Thread.java:1589) ~[na:na]
Caused by: java.lang.NumberFormatException: Expected a long but was 18446744073709550616 at line 1 column 19648 path $[23].purchased
        at com.google.gson.stream.JsonReader.nextLong(JsonReader.java:977) ~[white-lolpicker-client.jar:na]
        at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:319) ~[white-lolpicker-client.jar:na]
        ... 18 common frames omitted
```

_Same comments from #34_

**Comment by stirante** [comment]
Fixed in https://github.com/stirante/lol-client-java-api/pull/37
